require("core.plugin_config.lualine")
require("core.plugin_config.discord_rpc")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.colorschemes")
require("core.plugin_config.lsp")
require("core.plugin_config.web-devicons")
require("core.plugin_config.telescope")
